version: '3.8'

services:
  web-app:
    container_name: web_app_container
    build: ./web-app
    ports:
      - "5001:5000"
    depends_on:
      - mongodb

  ml-client:
    container_name: ml_client_container
    build: ./machine-learning-client/ML
    ports:
      - "6001:6000"
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb_container
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
